export const UPDATE_SELECTED_COUNTRY = 'UPDATE_SELECTED_COUNTRY';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_ERROR = 'GET_COUNTRIES_ERROR';
export const CHANGE_IS_FORM_SUBMITTED = 'TOGGLE_IS_FORM_SUBMITTED';
